### ISSUE TITLE
plex.py not working 

### ISSUE THREAD

**Issue by yarafie** [ReenigneArcher/web2tv#19]
### Describe the Bug

plex.py started today not working
attached is error log from run
[plexrunlog.txt](https://github.com/ReenigneArcher/web2tv/files/7888654/plexrunlog.txt)

### Code Snippets

''' Traceback (most recent call last):
  File "/storage/emulated/0/IPTV/web2tv/plex.py", line 3, in <module>
    import requests_cache
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests_cache/__init__.py", line 43, in <module>
    from .backends import *
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests_cache/backends/__init__.py", line 8, in <module>
    from .base import BaseCache, BaseStorage
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests_cache/backends/base.py", line 18, in <module>
    from ..serializers import init_serializer
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests_cache/serializers/__init__.py", line 6, in <module>
    from .preconf import (
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests_cache/serializers/preconf.py", line 26, in <module>
    base_stage = CattrStage()  #: Base stage for all serializer pipelines
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 32, in __init__
    self.converter = init_converter(factory)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests_cache/serializers/cattrs.py", line 67, in init_converter
    converter.register_structure_hook(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/cattr/converters.py", line 263, in register_structure_hook
    self._structure_func.register_cls_list([(cl, func)])
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/cattr/dispatch.py", line 57, in register_cls_list
    self._single_dispatch.register(cls, handler)
  File "/data/data/com.termux/files/usr/lib/python3.10/functools.py", line 856, in register
    raise TypeError(
TypeError: Invalid first argument to `register()`. ForwardRef('CachedResponse') is not a class.
'''

### Operating System and Version

termux android

### Python Version

3.10.2

**Comment by ReenigneArcher** [comment]
Please paste your attachment as a code block. Use three backticks "`" before and after the code block.

**Comment by yarafie** [comment]
> Please paste your attachment as a code block. Use three backticks "`" before and after the code block.

done

**Comment by ReenigneArcher** [comment]
Did you update your dependencies? Or are they automatically updated by chance?

**Comment by yarafie** [comment]
Only updated termux packages not any python also pluto.py is working

**Comment by ReenigneArcher** [comment]
pluto.py doesn't use `requests_cache`

**Comment by yarafie** [comment]
> pluto.py doesn't use `requests_cache`

Oh I see.  I don't recall doing any pip install updates but I regularly update termux packages

**Comment by ReenigneArcher** [comment]
I'm just guessing here, but try clearing any `.pyc` files and `__pycache__` directories.

plex.py is still working for me. I haven't updated any dependencies and run all of these scripts in a venv (https://python.land/virtual-environments/virtualenv). That's the best practice so that other packages don't mess with dependencies that you need. I'm also using Python 3.9.6. Have not tested on 3.10 yet.

**Comment by yarafie** [comment]
pip install --upgrade requests-cache

fixed it.
