### ISSUE TITLE
plex.py failing at the moment generating epg

### ISSUE THREAD

**Issue by yarafie** [ReenigneArcher/web2tv#27]
### Describe the Bug

plex.py failing at the moment generating epg

### Code Snippets

```python
'''Loading Grid for PlexTV, day: 1/2                                               url[1]: https://epg.provider.plex.tv/grid?type=1%2C4&sort=beginsAt&endsAt%3E=1654605000&beginsAt%3C=1654691400&X-Plex-Token=<MyPlexToken>&X-Plex-Language=en                                                                             Traceback (most recent call last):                                                File "/web2tv/plex.py", line 549, in <module>                                     main()                                                                        File "/web2tv/plex.py", line 248, in main                                         metadata_data['added_at'] = grid['MediaContainer']['Metadata'][y]['addedAt']KeyError: 'addedAt'''''
```

### Expected Behavior

generate epf

### Operating System and Version

ubuntu

### Python Version

Python 3.10.4

**Comment by ReenigneArcher** [comment]
Thanks for submitting the issue. It will probably be a while before I can look into this.

**Comment by yarafie** [comment]
Thanks.
